### ISSUE TITLE
Error: Stack traceback on export

### ISSUE THREAD

**Issue by lukeeingram** [RampantDespair/Aseprite-Exporter#1]
Hello, I tried using your script to export to Spine, but ran into an issue. Console log can be found below:

`Console
[string "internal"11: stack traceback:
[string "internal:: in function generic_mt_index"
/Users/lonk/Library/Application Support/Aseprite/scripts/Aseprite-Exporter.lua:65: in function exportSpriteLayers' /Users/lonk/Library/Application Support/Aseprite/scripts/Aseprite-Exporter.lua:40: in function 'export" /Users/lonk/Library/Application Support/Aseprite/Scripts/Aseprite-Exporter.lua:437: in main chunk: Field name does not exist`

![aseprite-export-script-error](https://github.com/RampantDespair/Aseprite-Exporter/assets/20246942/662c9151-15a1-47c7-8c00-caa225f94ede)

**Comment by RampantDespair** [comment]
@lukeeingram I believe I fixed your issue, try out [v2.4](https://github.com/RampantDespair/Aseprite-Exporter/releases/tag/v2.4) and let me know if it works for you now. :)
